// The texts of docs/wails/UX_COPY.md the checks look for, per language.
export const TEXTS = {
  en: {
    finished: 'Finished in',
    stopped: 'Stopped.',
    compileFailed: "Your program didn't run",
    run: 'Run',
    debug: 'Debug',
    stop: 'Stop',
    stopDebugging: 'Stop debugging',
    nextLine: 'Next line',
    runToHere: 'Run to here',
    justChanged: 'just changed',
    callStack: 'How you got here',
    goroutines: 'Goroutines',
    goToLine: 'Go to line',
    paused: 'Paused · line',
    tryThis: 'Try this:',
    closeChanges: 'Save changes to',
    save: 'Save',
    dontSave: "Don't save",
    welcome: 'Welcome to VizcachaIDE',
    next: 'Next',
    openHello: 'Open hello example',
    more: 'More',
    settings: 'Settings',
    unusedTitle: 'Variable "count" is never used',
    placeholderArgs: 'Program arguments',
    panicTitle: 'Writing to a map that was never created',
    placeholderStdin: 'Type here and press Enter to answer your program'
  },
  es: {
    finished: 'Terminó bien en',
    stopped: 'Detenido.',
    compileFailed: 'No se pudo ejecutar',
    run: 'Ejecutar',
    debug: 'Depurar',
    stop: 'Detener',
    stopDebugging: 'Terminar depuración',
    nextLine: 'Siguiente línea',
    runToHere: 'Ejecutar hasta aquí',
    justChanged: 'acaba de cambiar',
    callStack: 'Cómo llegaste aquí',
    goroutines: 'Goroutines',
    goToLine: 'Ir a la línea',
    paused: 'En pausa · línea',
    tryThis: 'Prueba esto:',
    closeChanges: '¿Guardar los cambios de',
    save: 'Guardar',
    dontSave: 'No guardar',
    welcome: 'Te damos la bienvenida a VizcachaIDE',
    next: 'Siguiente',
    openHello: 'Abrir el ejemplo «Hola»',
    more: 'Más',
    settings: 'Configuración',
    unusedTitle: 'La variable "count" nunca se usa',
    placeholderArgs: 'Argumentos del programa',
    panicTitle: 'Escritura en un map que nunca se creó',
    placeholderStdin: 'Escribe aquí y pulsa Enter para responder a tu programa'
  }
}
