// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Profiles() {
  return window['go']['bridge']['CodeLanguagesService']['Profiles']();
}

export function Tools() {
  return window['go']['bridge']['CodeLanguagesService']['Tools']();
}
