// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function Profiles():Promise<Array<domain.LanguageProfile>>;

export function Tools():Promise<Array<domain.ToolStatus>>;
