// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Eval(arg1, arg2) {
  return window['go']['bridge']['ConsoleService']['Eval'](arg1, arg2);
}

export function Reset(arg1) {
  return window['go']['bridge']['ConsoleService']['Reset'](arg1);
}
