// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function Eval(arg1:string):Promise<domain.ConsoleResult>;

export function Reset():Promise<void>;
