// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function Eval(arg1:domain.CodeLanguage,arg2:string):Promise<domain.ConsoleResult>;

export function Reset(arg1:domain.CodeLanguage):Promise<void>;
