// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Eval(arg1) {
  return window['go']['bridge']['ConsoleService']['Eval'](arg1);
}

export function Reset() {
  return window['go']['bridge']['ConsoleService']['Reset']();
}
