// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function RequestVariables(arg1:number):Promise<void>;

export function Resume():Promise<void>;

export function RunTo(arg1:domain.SourceLocation):Promise<void>;

export function SetBreakpoints(arg1:string,arg2:Array<number>):Promise<void>;

export function Start(arg1:string,arg2:Array<domain.Breakpoint>,arg3:string):Promise<void>;

export function StepInto():Promise<void>;

export function StepOut():Promise<void>;

export function StepOver():Promise<void>;

export function Stop():Promise<void>;
