// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FrameVariables(arg1) {
  return window['go']['bridge']['DebugService']['FrameVariables'](arg1);
}

export function RequestVariables(arg1) {
  return window['go']['bridge']['DebugService']['RequestVariables'](arg1);
}

export function Resume() {
  return window['go']['bridge']['DebugService']['Resume']();
}

export function RunTo(arg1) {
  return window['go']['bridge']['DebugService']['RunTo'](arg1);
}

export function SetBreakpoints(arg1, arg2) {
  return window['go']['bridge']['DebugService']['SetBreakpoints'](arg1, arg2);
}

export function Start(arg1, arg2, arg3) {
  return window['go']['bridge']['DebugService']['Start'](arg1, arg2, arg3);
}

export function StepInto() {
  return window['go']['bridge']['DebugService']['StepInto']();
}

export function StepOut() {
  return window['go']['bridge']['DebugService']['StepOut']();
}

export function StepOver() {
  return window['go']['bridge']['DebugService']['StepOver']();
}

export function Stop() {
  return window['go']['bridge']['DebugService']['Stop']();
}
