// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListTree(arg1) {
  return window['go']['bridge']['FilesService']['ListTree'](arg1);
}

export function OpenFolder() {
  return window['go']['bridge']['FilesService']['OpenFolder']();
}

export function ReadFile(arg1) {
  return window['go']['bridge']['FilesService']['ReadFile'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['bridge']['FilesService']['SaveFile'](arg1, arg2);
}
