// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseFolder() {
  return window['go']['bridge']['FilesService']['ChooseFolder']();
}

export function CreateFile(arg1, arg2) {
  return window['go']['bridge']['FilesService']['CreateFile'](arg1, arg2);
}

export function CreateFolder(arg1) {
  return window['go']['bridge']['FilesService']['CreateFolder'](arg1);
}

export function ListTree(arg1) {
  return window['go']['bridge']['FilesService']['ListTree'](arg1);
}

export function MoveToTrash(arg1) {
  return window['go']['bridge']['FilesService']['MoveToTrash'](arg1);
}

export function OpenFileDialog() {
  return window['go']['bridge']['FilesService']['OpenFileDialog']();
}

export function OpenFolder() {
  return window['go']['bridge']['FilesService']['OpenFolder']();
}

export function ReadFile(arg1) {
  return window['go']['bridge']['FilesService']['ReadFile'](arg1);
}

export function Rename(arg1, arg2) {
  return window['go']['bridge']['FilesService']['Rename'](arg1, arg2);
}

export function RevealInExplorer(arg1) {
  return window['go']['bridge']['FilesService']['RevealInExplorer'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['bridge']['FilesService']['SaveFile'](arg1, arg2);
}

export function SaveFileDialog(arg1, arg2) {
  return window['go']['bridge']['FilesService']['SaveFileDialog'](arg1, arg2);
}

export function UseLanguages(arg1) {
  return window['go']['bridge']['FilesService']['UseLanguages'](arg1);
}

export function UseShell(arg1) {
  return window['go']['bridge']['FilesService']['UseShell'](arg1);
}

export function WatchFiles(arg1) {
  return window['go']['bridge']['FilesService']['WatchFiles'](arg1);
}
