// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {app} from '../models';
import {bridge} from '../models';

export function ApplyTextEdits(arg1:Array<domain.FileEdit>):Promise<domain.EditSummary>;

export function ChooseFolder():Promise<string>;

export function Copy(arg1:string,arg2:string):Promise<void>;

export function CreateFile(arg1:string,arg2:string):Promise<void>;

export function CreateFolder(arg1:string):Promise<void>;

export function ListTree(arg1:string):Promise<domain.FileNode>;

export function MoveToTrash(arg1:string):Promise<void>;

export function OpenFileDialog():Promise<string>;

export function OpenFolder():Promise<domain.FileNode>;

export function ReadFile(arg1:string):Promise<string>;

export function Rename(arg1:string,arg2:string):Promise<void>;

export function RevealInExplorer(arg1:string):Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SaveFileDialog(arg1:string,arg2:string):Promise<string>;

export function UseLanguages(arg1:app.LanguageRegistry):Promise<bridge.FilesService>;

export function UseShell(arg1:app.SystemShell):Promise<bridge.FilesService>;

export function WatchFiles(arg1:Array<string>):Promise<void>;
