// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeDocument(arg1, arg2, arg3) {
  return window['go']['bridge']['LanguageService']['ChangeDocument'](arg1, arg2, arg3);
}

export function CloseDocument(arg1) {
  return window['go']['bridge']['LanguageService']['CloseDocument'](arg1);
}

export function Completion(arg1) {
  return window['go']['bridge']['LanguageService']['Completion'](arg1);
}

export function Definition(arg1) {
  return window['go']['bridge']['LanguageService']['Definition'](arg1);
}

export function DocumentHighlights(arg1) {
  return window['go']['bridge']['LanguageService']['DocumentHighlights'](arg1);
}

export function DocumentSymbols(arg1) {
  return window['go']['bridge']['LanguageService']['DocumentSymbols'](arg1);
}

export function Hover(arg1) {
  return window['go']['bridge']['LanguageService']['Hover'](arg1);
}

export function OpenDocument(arg1, arg2) {
  return window['go']['bridge']['LanguageService']['OpenDocument'](arg1, arg2);
}

export function SignatureHelp(arg1) {
  return window['go']['bridge']['LanguageService']['SignatureHelp'](arg1);
}
