// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function ChangeDocument(arg1:string,arg2:string,arg3:number):Promise<void>;

export function CloseDocument(arg1:string):Promise<void>;

export function Completion(arg1:domain.SourceLocation):Promise<Array<domain.CompletionItem>>;

export function Definition(arg1:domain.SourceLocation):Promise<domain.SourceLocation>;

export function DocumentHighlights(arg1:domain.SourceLocation):Promise<Array<domain.SourceRange>>;

export function DocumentSymbols(arg1:string):Promise<Array<domain.DocumentSymbol>>;

export function Hover(arg1:domain.SourceLocation):Promise<string>;

export function InlayHints(arg1:domain.SourceRange):Promise<Array<domain.InlayHint>>;

export function OpenDocument(arg1:string,arg2:string):Promise<void>;

export function SignatureHelp(arg1:domain.SourceLocation):Promise<domain.SignatureHelp>;
