// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1, arg2, arg3) {
  return window['go']['bridge']['PackagesService']['Add'](arg1, arg2, arg3);
}

export function Init(arg1, arg2, arg3) {
  return window['go']['bridge']['PackagesService']['Init'](arg1, arg2, arg3);
}

export function List(arg1, arg2) {
  return window['go']['bridge']['PackagesService']['List'](arg1, arg2);
}

export function Remove(arg1, arg2, arg3) {
  return window['go']['bridge']['PackagesService']['Remove'](arg1, arg2, arg3);
}

export function Tidy(arg1, arg2) {
  return window['go']['bridge']['PackagesService']['Tidy'](arg1, arg2);
}
