// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function Add(arg1:domain.CodeLanguage,arg2:string,arg3:string):Promise<void>;

export function Init(arg1:domain.CodeLanguage,arg2:string,arg3:string):Promise<void>;

export function List(arg1:domain.CodeLanguage,arg2:string):Promise<void>;

export function Remove(arg1:domain.CodeLanguage,arg2:string,arg3:string):Promise<void>;

export function Search(arg1:domain.CodeLanguage,arg2:string):Promise<Array<domain.PackageInfo>>;

export function Tidy(arg1:domain.CodeLanguage,arg2:string):Promise<void>;
