// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function Create(arg1:domain.CodeLanguage,arg2:string,arg3:string):Promise<domain.NewProject>;
