// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Build(arg1, arg2) {
  return window['go']['bridge']['RunService']['Build'](arg1, arg2);
}

export function Format(arg1) {
  return window['go']['bridge']['RunService']['Format'](arg1);
}

export function ModGet(arg1, arg2) {
  return window['go']['bridge']['RunService']['ModGet'](arg1, arg2);
}

export function ModInit(arg1, arg2) {
  return window['go']['bridge']['RunService']['ModInit'](arg1, arg2);
}

export function ModTidy(arg1) {
  return window['go']['bridge']['RunService']['ModTidy'](arg1);
}

export function Run(arg1, arg2) {
  return window['go']['bridge']['RunService']['Run'](arg1, arg2);
}

export function RunUntitled(arg1, arg2) {
  return window['go']['bridge']['RunService']['RunUntitled'](arg1, arg2);
}

export function SplitArguments(arg1) {
  return window['go']['bridge']['RunService']['SplitArguments'](arg1);
}

export function Stop() {
  return window['go']['bridge']['RunService']['Stop']();
}

export function Toolchain() {
  return window['go']['bridge']['RunService']['Toolchain']();
}

export function WriteInput(arg1) {
  return window['go']['bridge']['RunService']['WriteInput'](arg1);
}
