// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Build(arg1, arg2) {
  return window['go']['bridge']['RunService']['Build'](arg1, arg2);
}

export function Check(arg1) {
  return window['go']['bridge']['RunService']['Check'](arg1);
}

export function Format(arg1, arg2) {
  return window['go']['bridge']['RunService']['Format'](arg1, arg2);
}

export function Run(arg1, arg2) {
  return window['go']['bridge']['RunService']['Run'](arg1, arg2);
}

export function RunUntitled(arg1, arg2, arg3) {
  return window['go']['bridge']['RunService']['RunUntitled'](arg1, arg2, arg3);
}

export function SplitArguments(arg1) {
  return window['go']['bridge']['RunService']['SplitArguments'](arg1);
}

export function Stop() {
  return window['go']['bridge']['RunService']['Stop']();
}

export function WriteInput(arg1) {
  return window['go']['bridge']['RunService']['WriteInput'](arg1);
}
