// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function Format(arg1:string):Promise<string>;

export function Run(arg1:string,arg2:Array<string>):Promise<domain.RunConfiguration>;

export function RunUntitled(arg1:string,arg2:Array<string>):Promise<domain.RunConfiguration>;

export function Stop():Promise<void>;

export function Toolchain():Promise<domain.ToolchainInfo>;

export function WriteInput(arg1:string):Promise<void>;
