// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Format(arg1) {
  return window['go']['bridge']['RunService']['Format'](arg1);
}

export function Run(arg1, arg2) {
  return window['go']['bridge']['RunService']['Run'](arg1, arg2);
}

export function RunUntitled(arg1, arg2) {
  return window['go']['bridge']['RunService']['RunUntitled'](arg1, arg2);
}

export function Stop() {
  return window['go']['bridge']['RunService']['Stop']();
}

export function Toolchain() {
  return window['go']['bridge']['RunService']['Toolchain']();
}

export function WriteInput(arg1) {
  return window['go']['bridge']['RunService']['WriteInput'](arg1);
}
