// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Replace(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['bridge']['SearchService']['Replace'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function Search(arg1, arg2, arg3) {
  return window['go']['bridge']['SearchService']['Search'](arg1, arg2, arg3);
}
