// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function Replace(arg1:string,arg2:string,arg3:domain.SearchOptions,arg4:string,arg5:Array<string>,arg6:number,arg7:number):Promise<domain.ReplaceResult>;

export function Search(arg1:string,arg2:string,arg3:domain.SearchOptions):Promise<domain.SearchResult>;
