// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {bridge} from '../models';

export function Get():Promise<domain.Settings>;

export function PickExecutable(arg1:string):Promise<Array<domain.ToolStatus>>;

export function ResolvedLanguage():Promise<string>;

export function Save(arg1:domain.Settings):Promise<void>;

export function UseTools(arg1:bridge.ExecutablePicker):Promise<bridge.SettingsService>;
