// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function Get():Promise<domain.Settings>;

export function Save(arg1:domain.Settings):Promise<void>;
