// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close(arg1) {
  return window['go']['bridge']['TerminalService']['Close'](arg1);
}

export function Resize(arg1, arg2, arg3) {
  return window['go']['bridge']['TerminalService']['Resize'](arg1, arg2, arg3);
}

export function Start(arg1, arg2, arg3) {
  return window['go']['bridge']['TerminalService']['Start'](arg1, arg2, arg3);
}

export function Write(arg1, arg2) {
  return window['go']['bridge']['TerminalService']['Write'](arg1, arg2);
}
