// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function Check():Promise<domain.UpdateState>;

export function Download():Promise<void>;

export function Install():Promise<void>;

export function State():Promise<domain.UpdateState>;
