// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Check() {
  return window['go']['bridge']['UpdatesService']['Check']();
}

export function Download() {
  return window['go']['bridge']['UpdatesService']['Download']();
}

export function Install() {
  return window['go']['bridge']['UpdatesService']['Install']();
}

export function State() {
  return window['go']['bridge']['UpdatesService']['State']();
}
