// Package i18n translates the texts the backend produces (IDE errors, explanations).
// The catalogs are generated by tools/po2json and embedded in the binary.
package i18n

import (
	"embed"
	"fmt"

	"encoding/json"
	goi18n "github.com/nicksnyder/go-i18n/v2/i18n"
	"golang.org/x/text/language"
)

//go:embed locales/*.json
var localeFiles embed.FS

// Supported lists the language tags that have a catalog.
var Supported = []string{"en", "es"}

// NewBundle loads every embedded catalog. English is the default language.
func NewBundle() (*goi18n.Bundle, error) {
	bundle := goi18n.NewBundle(language.English)
	bundle.RegisterUnmarshalFunc("json", json.Unmarshal)
	for _, tag := range Supported {
		path := fmt.Sprintf("locales/%s.json", tag)
		if _, err := bundle.LoadMessageFileFS(localeFiles, path); err != nil {
			return nil, fmt.Errorf("load catalog %s: %w", tag, err)
		}
	}
	return bundle, nil
}

// Translator translates message ids into one language.
type Translator struct {
	localizer *goi18n.Localizer
}

// NewTranslator returns a translator for a language ("en" or "es"); any other value falls back to English.
func NewTranslator(bundle *goi18n.Bundle, lang string) *Translator {
	return &Translator{localizer: goi18n.NewLocalizer(bundle, lang, "en")}
}

// T returns the text of id with its placeholders filled in. A missing id returns the id itself.
func (t *Translator) T(id string, data map[string]any) string {
	text, err := t.localizer.Localize(&goi18n.LocalizeConfig{MessageID: id, TemplateData: data})
	if err != nil {
		return id
	}
	return text
}

// Plural is like T for messages with "one" and "other" forms; count selects the form and fills {{.count}}.
func (t *Translator) Plural(id string, count int, data map[string]any) string {
	merged := map[string]any{"count": count}
	for k, v := range data {
		merged[k] = v
	}
	text, err := t.localizer.Localize(&goi18n.LocalizeConfig{MessageID: id, PluralCount: count, TemplateData: merged})
	if err != nil {
		return id
	}
	return text
}
